"""Deterministic contracts for official and sealed read-only source monitoring."""

from .contracts import (
    MAX_ADAPTER_KEY_CHARS,
    MAX_CHECKPOINT_BYTES,
    MAX_ERROR_CODE_CHARS,
    MAX_ERROR_MESSAGE_CHARS,
    MAX_ERROR_SCOPE_CHARS,
    MAX_ETAG_CHARS,
    MAX_JSON_DEPTH,
    MAX_LAST_MODIFIED_CHARS,
    MAX_MARKET_CALLS_PER_POLL,
    MAX_NATIVE_INTEGER,
    MAX_OBSERVED_ITEMS_PER_POLL,
    MAX_SOURCE_ERRORS_PER_POLL,
    FUTU_ANOMALY_SOURCE_CHANNEL,
    OFFICIAL_SOURCE_CHANNEL,
    OFFICIAL_SOURCE_CLASS,
    READONLY_MARKET_SOURCE_CLASS,
    AdapterPollResult,
    SourceMonitoringContractError,
    SourcePollError,
    canonical_json,
    canonical_sha256,
    normalize_adapter_key,
    normalize_checkpoint,
)

__all__ = [
    "MAX_ADAPTER_KEY_CHARS",
    "MAX_CHECKPOINT_BYTES",
    "MAX_ERROR_CODE_CHARS",
    "MAX_ERROR_MESSAGE_CHARS",
    "MAX_ERROR_SCOPE_CHARS",
    "MAX_ETAG_CHARS",
    "MAX_JSON_DEPTH",
    "MAX_LAST_MODIFIED_CHARS",
    "MAX_MARKET_CALLS_PER_POLL",
    "MAX_NATIVE_INTEGER",
    "MAX_OBSERVED_ITEMS_PER_POLL",
    "MAX_SOURCE_ERRORS_PER_POLL",
    "FUTU_ANOMALY_SOURCE_CHANNEL",
    "OFFICIAL_SOURCE_CHANNEL",
    "OFFICIAL_SOURCE_CLASS",
    "READONLY_MARKET_SOURCE_CLASS",
    "AdapterPollResult",
    "SourceMonitoringContractError",
    "SourcePollError",
    "canonical_json",
    "canonical_sha256",
    "normalize_adapter_key",
    "normalize_checkpoint",
]
